language: python
sudo: false
cache:
  pip: true
  directories:
    - eggs
python:
  - "2.7"
  - "3.6"
  - "3.7"
firefox: "latest"
env:
  matrix:
    - PLONE_VERSION=4.3.x BUILDOUT=buildout
    - PLONE_VERSION=5.0.x BUILDOUT=buildout
    - PLONE_VERSION=5.1.x BUILDOUT=buildout
    - PLONE_VERSION=5.2.x BUILDOUT=buildout
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver && tar zxvf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip install -r requirements.txt
services:
  - xvfb
before_script:
  - "export ROBOT_HTTP_PORT=55001"
script:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - buildout -c travis.cfg
  - bin/test
