language: python
cache:
  pip: true
  directories:
    - eggs
python:
  - 2.7
  - 3.6
  - 3.7
env:
  - PLONE_VERSION=5.1
  - PLONE_VERSION=5.2
jobs:
  exclude:
    - python: 3.6
      env: PLONE_VERSION=5.1
    - python: 3.7
      env: PLONE_VERSION=5.1
matrix:
  fast_finish: true
firefox: "latest"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver && tar zxvf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - virtualenv .
  - sed -i "s/5.2-latest/$PLONE_VERSION-latest/g" buildout.cfg requirements.txt
  - bin/pip install -r requirements.txt
  - bin/buildout -t 30
services:
  - xvfb
before_script:
  - "export ROBOT_HTTP_PORT=55001"
script: bin/test
