language: python
sudo: false
cache:
  pip: true
  directories:
    - eggs
python:
  - "2.7"
  - "3.6"
  - "3.7"
firefox: "latest"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver && tar zxvf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - python bootstrap.py
  - bin/buildout -t 30
services:
  - xvfb
before_script:
  - "export ROBOT_HTTP_PORT=55001"
script: bin/test
